# Generated by Django 5.0.1 on 2024-01-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
