# Generated by Django 4.2.10 on 2024-02-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
