# Generated by Django 4.2.10 on 2024-02-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
