# Generated by Django 4.2.11 on 2024-03-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='labels',
            new_name='label',
        ),
    ]
