# Generated by Django 4.2.11 on 2024-03-19 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
        ('labels', '0001_initial'),
        ('tasks', '0002_rename_labels_tasksmodel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='label',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='labels', through='tasks.LabelsOnTasks', to='labels.labelsmodel', verbose_name='Labels'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='status',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='statuses.statusesmodel', verbose_name='Status'),
        ),
    ]
