# Generated by Django 4.2.10 on 2024-02-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_statusesmodel_options_alter_statusesmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusesmodel',
            old_name='name',
            new_name='status',
        ),
    ]
