# Generated by Django 4.2.10 on 2024-02-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_rename_name_statusesmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusesmodel',
            old_name='status',
            new_name='name',
        ),
    ]
